export const SUCCEED_TO_SIGNUP = "SUCCEED_TO_SIGNUP";
export const FAILED_TO_SIGNUP = "FAILED_TO_SIGNUP";

export const USERTYPE_UPDATED = "USERTYPE_UPDATED";
export const SIGNUP_INFO_UPDATED = "SIGNUP_INFO_UPDATED";
export const SIGNUPSTEP_UPDATED = "SIGNUPSTEP_UPDATED";

export const SUCCEED_TO_SIGNIN = "SUCCEED_TO_SIGNIN";
export const FAILED_TO_SIGNIN = "FAILED_TO_SIGNIN";
