/* AUTH ACTIONS */
// export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const SIGNOUT = 'SIGNOUT';
export const GET_USER = 'GET_USER';
export const REMOVE_USER = 'REMOVE_USER';

/* POST ACTIONS */
export const SUCCEED_TO_GET_ALLPOST = 'SUCCEED_TO_GET_ALLPOST';
export const FAILED_TO_GET_ALLPOST = 'FAILED_TO_GET_ALLPOST';

export const SUCCEED_TO_GET_POST_BY_USERID = 'SUCCEED_TO_GET_POST_BY_USERID';
export const FAILED_TO_GET_POST_BY_USERID = 'FAILED_TO_GET_POST_BY_USERID';

export const SUCCEED_TO_GET_POST_BY_POSTID = 'SUCCEED_TO_GET_POST_BY_POSTID';
export const FAILED_TO_GET_POST_BY_POSTID = 'FAILED_TO_GET_POST_BY_POSTID';

export const SUCCEED_TO_UPLOAD_POST = 'SUCCEED_TO_UPLOAD_POST';
export const FAILED_TO_UPLOAD_POST = 'FAILED_TO_UPLOAD_POST';

export const SUCCEED_TO_DELETE_POST = 'SUCCEED_TO_DELETE_POST';
export const FAILED_TO_DELETE_POST = 'FAILED_TO_DELETE_POST';

export const SUCCEED_TO_POST_LIKE = 'SUCCEED_TO_POST_LIKE';
export const FAILED_TO_POST_LIKE = 'FAILED_TO_POST_LIKE';

export const SUCCEED_TO_DELETE_LIKE = 'SUCCEED_TO_DELETE_LIKE';
export const FAILED_TO_DELETE_LIKE = 'FAILED_TO_DELETE_LIKE';
