/* AUTH ACTIONS */
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const SUCCEED_TO_SIGNIN = "SUCCEED_TO_SIGNIN";
export const FAILED_TO_SIGNIN = "FAILED_TO_SIGNIN";

export const SUCCEED_TO_SIGNOUT = "SUCCEED_TO_SIGNOUT";

export const SUCCEED_TO_GET_USER = "SUCCEED_TO_GET_USER";
export const FAILED_TO_GET_USER = "FAILED_TO_GET_USER";

/* USER ACTIONS */
export const SUCCEED_TO_SIGNUP = "SUCCEED_TO_SIGNUP";
export const FAILED_TO_SIGNUP = "FAILED_TO_SIGNUP";

export const SUCCEED_TO_GET_USER_BY_USERNAME = "SUCCEED_TO_GET_USER_BY_USERNAME";
export const FAILED_TO_GET_USER_BY_USERNAME = "FAILED_TO_GET_USER_BY_USERNAME";

/* POST ACTIONS */
export const SUCCEED_TO_GET_ALLPOST = "SUCCEED_TO_GET_ALLPOST";
export const FAILED_TO_GET_ALLPOST = "FAILED_TO_GET_ALLPOST";

export const SUCCEED_TO_GET_POST_BY_USERID = "SUCCEED_TO_GET_POST_BY_USERID";
export const FAILED_TO_GET_POST_BY_USERID = "FAILED_TO_GET_POST_BY_USERID";

export const SUCCEED_TO_GET_POST_BY_POSTID = "SUCCEED_TO_GET_POST_BY_POSTID";
export const FAILED_TO_GET_POST_BY_POSTID = "FAILED_TO_GET_POST_BY_POSTID";

export const SUCCEED_TO_UPLOAD_POST = "SUCCEED_TO_UPLOAD_POST";
export const FAILED_TO_UPLOAD_POST = "FAILED_TO_UPLOAD_POST";

export const SUCCEED_TO_DELETE_POST = "SUCCEED_TO_DELETE_POST";
export const FAILED_TO_DELETE_POST = "FAILED_TO_DELETE_POST";

export const SUCCEED_TO_POST_LIKE = "SUCCEED_TO_POST_LIKE";
export const FAILED_TO_POST_LIKE = "FAILED_TO_POST_LIKE";

